#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "9626b4a440c84503a46b7ed67647477a"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "c64c8e46-dab0-4700-bd41-ef2a8835daa1"
preview_database_id = "f591d1c7-0060-4d35-a146-099ec27b49b1"
migrations_dir = "app/drizzle"
